#!/usr/bin/env bash
#install ngnix x with custom header

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx start