#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=1

while [[ "$i" -le 10 ]]
do
	if [[ "$i" -eq 9 ]]
	then
		printf "Hi\n"
	else
		printf "Best School\n"
	fi
	i=$(( i+1 ))
done
