#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=1

while [[ "$i" -le 20 ]]
do
	printf "%d\n" $i
	if [[ "$i" -eq 4 ]]
	then
		printf "bad luck from China\n"
	elif [[ "$i" -eq 8 ]]
	then
		printf "bad luck from Japan\n"
	elif [[ "$i" -eq 17 ]]
	then
		printf "bad luck from Italy\n"
	fi
	i=$(( i+1 ))
done
